#!/bin/bash

# Скрипт установки FRP клиента
#
# Использование:
#   sudo ./install-frp.sh [SERVER_ADDR] [AUTH_TOKEN] [USERNAME]
#
# Примеры:
#   sudo ./install-frp.sh course.prafdin.ru mytoken prafdin

set -e

# Параметры
SERVER_ADDR=${1:-"course.prafdin.ru"}
AUTH_TOKEN=${2:-"mytoken"}
USERNAME=${3:-"prafdin"}
TCP_PORT=${4:-"2022"}

echo "🚀 Установка FRP клиента..."
echo "📋 Параметры:"
echo "   Сервер: $SERVER_ADDR"
echo "   Токен: ${AUTH_TOKEN:0:8}***"
echo "   Пользователь: $USERNAME"
echo "   TCP порт: $TCP_PORT"
echo ""

# Проверяем права суперпользователя
if [[ $EUID -ne 0 ]]; then
   echo "❌ Этот скрипт должен запускаться с правами root (sudo)"
   echo ""
   echo "📝 Использование:"
   echo "   sudo ./install-frp.sh [SERVER_ADDR] [AUTH_TOKEN] [USERNAME] [TCP_PORT]"
   echo ""
   echo "🔧 Примеры:"
   echo "   sudo ./install-frp.sh course.prafdin.ru mytoken prafdin 2022"
   exit 1
fi

# Создаем директорию для FRP
mkdir -p /etc/frp
mkdir -p /var/log/frp

if command -v frpc >/dev/null 2>&1; then
   echo "✅ FRP клиент (frpc) уже установлен: $(frpc -v 2>/dev/null || echo "версия неизвестна")"
   echo "⏭ Пропускаем установку..."
else
   echo "📥 Скачиваем и устанавливаем FRP как systemd сервис..."
   curl -fsSL https://gist.github.com/lawrenceching/41244a182307940cc15b45e3c4997346/raw/0576ea85d898c965c3137f7c38f9815e1233e0d1/install-frp-as-systemd-service.sh | bash
fi

# Генерируем конфигурацию
echo "⚙️  Генерируем конфигурацию..."
cat > /etc/frp/frpc.toml << EOF
# FRP Client Configuration - Generated by install-frp.sh

serverAddr = "$SERVER_ADDR"
serverPort = 7000

auth.method = "token"
auth.token = "$AUTH_TOKEN"

# Прокси для webhook сервера
[[proxies]]
name = "hook-$USERNAME"
type = "http"
localIP = "127.0.0.1"
localPort = 8080
customDomains = ["webhook.$USERNAME.$SERVER_ADDR"]

# Прокси для продакшн приложения
[[proxies]]
name = "app-$USERNAME"
type = "http"
localIP = "127.0.0.1"
localPort = 8181
customDomains = ["app.$USERNAME.$SERVER_ADDR"]

# Прокси для тестового приложения
[[proxies]]
name = "app-$USERNAME"
type = "http"
localIP = "127.0.0.1"
localPort = 8282
customDomains = ["app-test.$USERNAME.$SERVER_ADDR"]

# Прокси для SSH (для GitHub Actions)
[[proxies]]
name = "ssh-$USERNAME"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = $TCP_PORT
EOF

echo "✅ Конфигурация сгенерирована в /etc/frp/frpc.toml"

# Устанавливаем права доступа
chown -R root:root /etc/frp
chmod 644 /etc/frp/frpc.toml
chown -R frp:frp /var/log/frp 2>/dev/null || echo "⚠️  Пользователь frp не найден (нормально для некоторых установок)"

echo "🔧 Перезагружаем systemd и запускаем FRP клиент..."
systemctl daemon-reload
systemctl enable frpc
systemctl start frpc
systemctl restart frpc

echo "📊 Проверяем статус FRP клиента..."
systemctl status frpc --no-pager

echo ""
echo "✅ FRP клиент установлен и запущен!"
echo ""
echo "🔍 Полезные команды:"
echo "   sudo systemctl status frpc     # Проверить статус"
echo "   sudo systemctl restart frpc    # Перезапустить"
echo "   sudo journalctl -u frpc -f     # Смотреть логи"
echo "   sudo nano /etc/frp/frpc.toml   # Редактировать конфиг"
echo ""
echo "🌐 URLs для вашей конфигурации:"
echo "   Webhook URL: http://webhook.$USERNAME.$SERVER_ADDR"
echo "   App URLs: http://app.$USERNAME.$SERVER_ADDR http://app-test.$USERNAME.$SERVER_ADDR"
echo "   SSH доступ: ssh user@$SERVER_ADDR -p $TCP_PORT (для GitHub Actions)"
echo ""
echo "⚙️  Для изменения конфигурации отредактируйте:"
echo "   /etc/frp/frpc.toml"