---
- name: Deploy Docker Container
  hosts: all
  become: yes
  vars:
    image_name: "ghcr.io/{{ github_repository_owner | default('prafdin') }}/devops-demo-website"
    image_tag: latest
    
  tasks:
    - name: Pull Docker image from registry
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull
        
    - name: Stop and remove existing container (if exists)
      docker_container:
        name: "demo-website-{{ deploy_env | default('production') }}"
        state: absent
      ignore_errors: yes
      
    - name: Run Docker container for development
      docker_container:
        name: "demo-website-develop"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:80"
        env:
          DEPLOY_ENV: develop
      when: deploy_env | default('production') == 'develop'
      
    - name: Run Docker container for production
      docker_container:
        name: "demo-website-production"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "8181:80"
        env:
          DEPLOY_ENV: production
      when: deploy_env | default('production') == 'production'
      
    - name: Wait for container to be ready
      wait_for:
        port: "{{ '8080' if (deploy_env | default('production')) == 'develop' else '8181' }}"
        host: localhost
        delay: 5
        timeout: 30