---
- name: Deploy Multi-Container Application with Docker Compose
  hosts: all
  become: yes
  vars:
    frontend_image: "ghcr.io/{{ github_repository_owner | default('prafdin') }}/devops-demo-website"
    backend_image: "ghcr.io/{{ github_repository_owner | default('prafdin') }}/devops-demo-website-backend"
    image_tag: "{{ image_tag | default('latest') }}"
    deployment_dir: "/opt/demo-website-{{ deploy_env }}"
  tasks:
    - name: Create deployment directory
      file:
        path: "{{ deployment_dir }}"
        state: directory
        mode: '0755'

    - name: Pull Docker images
      docker_image:
        name: "{{ item }}"
        tag: "{{ image_tag }}"
        source: pull
      loop:
        - "{{ frontend_image }}"
        - "{{ backend_image }}"

    - name: Copy docker-compose files
      copy:
        src: "{{ item.src }}"
        dest: "{{ deployment_dir }}/{{ item.dest }}"
        mode: '0644'
      loop:
        - { src: "../docker-compose.yml", dest: "docker-compose.yml" }
        - { src: "../docker-compose.{{ deploy_env }}.yml", dest: "docker-compose.{{ deploy_env }}.yml" }

    - name: Start services with Docker Compose v2
      community.docker.docker_compose_v2:
        project_src: /opt/demo-website
        files:
          - docker-compose.yml
          - "docker-compose.{{ deploy_env }}.yml"
        state: present
        scale:
          backend: 3
      environment:
        IMAGE_TAG: "{{ image_tag }}"
        
    - name: Wait for application to be ready
      wait_for:
        port: "{{ '8080' if deploy_env == 'develop' else '8181' }}"
        host: localhost
        delay: 10
        timeout: 60