name: Deploy dev

on:
  push:
    branches:
      - feature/*

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development
      container_name: devops-demo-website-DEV
      port: "8282"