name: Deploy reusable

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      container_name:
        required: true
        type: string
      port:
        required: true
        type: string

jobs:
  pipeline:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout код
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/devops-demo-website:${{ github.sha }} .

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/devops-demo-website:${{ github.sha }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          port: ${{ vars.DEPLOY_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/devops-demo-website:${{ github.sha }}"
            export CONTAINER_NAME="${{ inputs.container_name }}"

            docker pull $IMAGE_NAME
            docker rm -f $CONTAINER_NAME || true
            docker run -d \
              --name $CONTAINER_NAME \
              -p ${{ inputs.port }}:80 \
              $IMAGE_NAME