name: Deploy pipeline

on:
  push:
    branches:
      - feature/*

jobs:
  pipeline:
    environment: development
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout код
      uses: actions/checkout@v4
      
    - name: Запуск тестов
      run: |
        echo "🧪 Запуск тестов на GitHub runner..."
        ./test.sh

    - name: Build Docker image
      run: |
        echo "🐳 Сборка Docker образа..."
        docker build -t ghcr.io/${{ github.repository_owner }}/devops-demo-website:${{ github.sha }} .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: |
        echo "📦 Отправка образа в registry..."
        docker push ghcr.io/${{ github.repository_owner }}/devops-demo-website:${{ github.sha }}

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.DEPLOY_HOST }}
        username: ${{ vars.DEPLOY_USER }}
        port: ${{ vars.DEPLOY_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          export IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/devops-demo-website:${{ github.sha }}"
          export CONTAINER_NAME="devops-demo-website-DEV"
          docker pull $IMAGE_NAME
          docker rm -f $CONTAINER_NAME || true
          docker run -d \
            --name $CONTAINER_NAME \
            -p 8282:80 \
            $IMAGE_NAME
