name: Deploy PROD

on:
  push:
    branches:
      - docker-compose-demo

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: production
      container_name: devops-demo-website-PROD
      port: "8181"