name: Deploy reusable

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      container_name:
        required: true
        type: string
      port:
        required: true
        type: string

jobs:
  pipeline:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout код
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/devops-demo-website:${{ github.sha }} .
          docker build -t ghcr.io/${{ github.repository_owner }}/devops-demo-website-backend:${{ github.sha }} ./backend

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/devops-demo-website:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/devops-demo-website-backend:${{ github.sha }}

      - name: Create .env file
        run: |
          echo "FRONTEND_IMAGE=ghcr.io/${{ github.repository_owner }}/devops-demo-website:${{ github.sha }}" > .env
          echo "BACKEND_IMAGE=ghcr.io/${{ github.repository_owner }}/devops-demo-website-backend:${{ github.sha }}" >> .env
          echo "PORT=${{ inputs.port }}" >> .env
          echo "COMPOSE_PROJECT_NAME=${{ inputs.environment }}" >> .env

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          port: ${{ vars.DEPLOY_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./docker-compose.yml
          target: /opt/app/${{ inputs.environment }}

      - name: Copy .env to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          port: ${{ vars.DEPLOY_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./.env
          target: /opt/app/${{ inputs.environment }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          port: ${{ vars.DEPLOY_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -x
            docker compose up -d --pull always --remove-orphans